export const productsData = [
  // 1. TEAS & COFFEES - Green Tea (3 products)
  {
    id: 1,
    name: "Detox Green Tea",
    brand: "Taurus",
    price: 599,
    salePrice: 499,
    catId: 1,
    subCatId: 1,
    description: "7-day green tea blend crafted for daily detox support and light refreshment.",
    faqs: ["How to use?", "Can I drink it daily?", "Best time to consume?"],
    ingredients: "Green Tea, Dandelion, Nettle, Licorice Root, Lemon Peel, Ginger, Tulsi",
    boxSize: "100g",
    material: "Matte black tin",
    sku: "GRN-DET-100",
    offers: ["Buy 2 Get 1 20% OFF", "Free Shipping over ₹999"],
    image: "greenTea2"
  },
  {
    id: 2,
    name: "Tulsi Green Tea",
    brand: "Taurus",
    price: 549,
    salePrice: 449,
    catId: 1,
    subCatId: 1,
    description: "Refreshing green tea with tulsi and warming spices for daily wellness.",
    faqs: ["Does it contain caffeine?", "Can I have it twice a day?", "Can I add honey?"],
    ingredients: "Green Tea, Tulsi, Giloy, Ginger, Black Pepper, Cardamom",
    boxSize: "100g",
    material: "Glass jar with bamboo lid",
    sku: "GRN-TUL-100",
    offers: ["Free Immunity Guide"],
    image: "tulsigreentea"
  },
  {
    id: 3,
    name: "Hibiscus Tea",
    brand: "Taurus",
    price: 499,
    salePrice: 399,
    catId: 1,
    subCatId: 1,
    description: "Floral herbal tea made for a refreshing cup with a bright, tangy taste.",
    faqs: ["Can it be served cold?", "Is it caffeine free?", "Can I take it at night?"],
    ingredients: "Hibiscus, Rose Petals, Lemongrass, Licorice",
    boxSize: "75g",
    material: "Kraft pouch",
    sku: "HIB-TEA-075",
    offers: ["Combo with Rose Toner 15% OFF"],
    image: "teaHibiscus"
  },

  // 1. TEAS & COFFEES - Wellness Tea (6 products)
  {
    id: 4,
    name: "Golden Milk Mix",
    brand: "Taurus",
    price: 699,
    salePrice: 599,
    catId: 1,
    subCatId: 2,
    description: "Comforting golden milk mix for evening rituals and warm nourishment.",
    faqs: ["Can I mix it with water?", "Is it suitable before bed?", "Can I add jaggery?"],
    ingredients: "Turmeric, Black Pepper, Cardamom, Cinnamon, Ginger, Ashwagandha",
    boxSize: "150g",
    material: "Glass jar",
    sku: "GLD-MLK-150",
    offers: ["Free Golden Milk Mug"],
    image: "goldenMilkMix"
  },
  {
    id: 5,
    name: "Digestive Tea",
    brand: "Taurus",
    price: 449,
    salePrice: 399,
    catId: 1,
    subCatId: 2,
    description: "A soothing post-meal herbal tea made for everyday digestive comfort.",
    faqs: ["Should I drink it after food?", "Can kids consume it?", "How many cups per day?"],
    ingredients: "Fennel, Cumin, Ajwain, Mint, Coriander, Ginger",
    boxSize: "100g",
    material: "Kraft box",
    sku: "DIG-TEA-100",
    offers: ["Buy 3 Tea Pack ₹99 OFF"],
    image: "digestiveTea"
  },
  {
    id: 6,
    name: "Sleep Support Tea",
    brand: "Taurus",
    price: 649,
    salePrice: 549,
    catId: 1,
    subCatId: 2,
    description: "Gentle bedtime tea with calming herbs for a peaceful nighttime routine.",
    faqs: ["How long before sleep should I take it?", "Is it caffeine free?", "Can I take it daily?"],
    ingredients: "Chamomile, Ashwagandha, Lavender, Valerian, Passionflower",
    boxSize: "75g",
    material: "Tin can",
    sku: "SLP-TEA-075",
    offers: ["Free Sleep Tracker PDF"],
    image: "sleepSupportTea"
  },
  {
    id: 7,
    name: "Ginger Lemongrass Tea",
    brand: "Taurus",
    price: 429,
    salePrice: 379,
    catId: 1,
    subCatId: 2,
    description: "Bright and zesty tea blend ideal for a fresh start to the day.",
    faqs: ["Can I drink it on an empty stomach?", "Does it taste spicy?", "Can I add lemon?"],
    ingredients: "Ginger, Lemongrass, Tulsi, Mint, Lemon Peel",
    boxSize: "100g",
    material: "Glass jar",
    sku: "GLM-TEA-100",
    offers: ["Free Tea Strainer"],
    image: "lemontea"
  },
  {
    id: 8,
    name: "Tulsi Ashwagandha Tea",
    brand: "Taurus",
    price: 599,
    salePrice: 499,
    catId: 1,
    subCatId: 2,
    description: "Daily herbal tea with adaptogenic herbs for a calm and balanced cup.",
    faqs: ["Can I take it in the evening?", "Is it strong in taste?", "Can I mix with honey?"],
    ingredients: "Tulsi, Ashwagandha, Brahmi, Shankhpushpi",
    boxSize: "100g",
    material: "Matte black tin",
    sku: "TUL-ASH-100",
    offers: ["Stress Relief Guide"],
    image: "tulsitea"
  },
  {
    id: 9,
    name: "Chamomile Tea",
    brand: "Taurus",
    price: 529,
    salePrice: 449,
    catId: 1,
    subCatId: 2,
    description: "Light floral tea crafted for a relaxing evening beverage.",
    faqs: ["Can I drink it every night?", "Can I serve it iced?", "Does it contain tea leaves?"],
    ingredients: "Chamomile, Lavender, Rose, Mint",
    boxSize: "75g",
    material: "Glass jar",
    sku: "CHM-TEA-075",
    offers: ["Buy 2 Sleep Tea 15% OFF"],
    image: "leaves"
  },

  // 2. HERBAL SUPPLEMENTS - Ayurvedic Powders (5 products)
  {
    id: 10,
    name: "Ashwagandha Powder",
    brand: "Taurus",
    price: 999,
    salePrice: 799,
    catId: 2,
    subCatId: 3,
    description: "Classic ashwagandha root powder for daily herbal supplementation.",
    faqs: ["How should I consume it?", "Can I mix it with milk?", "What is the serving size?"],
    ingredients: "Ashwagandha Root",
    boxSize: "200g",
    material: "Amber glass jar",
    sku: "ASH-PWD-200",
    offers: ["3rd bottle 50% OFF"],
    image: "ashwa"
  },
  {
    id: 11,
    name: "Triphala Powder",
    brand: "Taurus",
    price: 699,
    salePrice: 599,
    catId: 2,
    subCatId: 3,
    description: "Traditional herbal powder blend used in everyday wellness routines.",
    faqs: ["Best time to take it?", "Can I mix in warm water?", "Is daily use okay?"],
    ingredients: "Amla, Haritaki, Bibhitaki",
    boxSize: "150g",
    material: "Matte black jar",
    sku: "TRI-PWD-150",
    offers: ["Free Detox Guide"],
    image: "triphla"
  },
  {
    id: 12,
    name: "Shatavari Powder",
    brand: "Taurus",
    price: 899,
    salePrice: 749,
    catId: 2,
    subCatId: 3,
    description: "Pure shatavari powder designed for simple daily use.",
    faqs: ["Can it be taken with milk?", "Is it suitable for everyday use?", "How much should I take?"],
    ingredients: "Shatavari Root",
    boxSize: "100g",
    material: "Glass jar",
    sku: "SHA-PWD-100",
    offers: ["Women Wellness Guide"],
    image: "shatawari"
  },
  {
    id: 13,
    name: "Brahmi Powder",
    brand: "Taurus",
    price: 799,
    salePrice: 699,
    catId: 2,
    subCatId: 3,
    description: "Fine herbal powder for adding to your daily wellness routine.",
    faqs: ["Can I mix it with water?", "What does it taste like?", "Can I combine it with honey?"],
    ingredients: "Brahmi",
    boxSize: "100g",
    material: "Glass jar",
    sku: "BRA-PWD-100",
    offers: ["Wellness Combo Discount"],
    image: "ashwa2"
  },
  {
    id: 14,
    name: "Giloy Powder",
    brand: "Taurus",
    price: 649,
    salePrice: 549,
    catId: 2,
    subCatId: 3,
    description: "Single-ingredient giloy powder for easy daily supplementation.",
    faqs: ["How should I consume it?", "Can I take it in the morning?", "Can it be mixed with juice?"],
    ingredients: "Giloy",
    boxSize: "100g",
    material: "Glass jar",
    sku: "GIL-PWD-100",
    offers: ["Combo with Tulsi Green Tea"],
    image: "immunity"
  },

  // 2. HERBAL SUPPLEMENTS - Superfoods (8 products)
  {
    id: 15,
    name: "Moringa Powder",
    brand: "Taurus",
    price: 699,
    salePrice: 599,
    catId: 2,
    subCatId: 4,
    description: "Nutrient-rich moringa leaf powder for smoothies and daily use.",
    faqs: ["Can I add it to smoothies?", "What is the serving size?", "Can I take it every day?"],
    ingredients: "Moringa Leaves",
    boxSize: "200g",
    material: "Glass jar",
    sku: "MOR-PWD-200",
    offers: ["Buy 2 Superfoods 10% OFF"],
    image: "moringa"
  },
  {
    id: 16,
    name: "Wheatgrass Powder",
    brand: "Taurus",
    price: 749,
    salePrice: 629,
    catId: 2,
    subCatId: 4,
    description: "Fine wheatgrass powder for juices, smoothies, and green blends.",
    faqs: ["Can I mix it in water?", "Should I consume it in the morning?", "Can I combine it with moringa?"],
    ingredients: "Wheatgrass",
    boxSize: "100g",
    material: "Frosted jar",
    sku: "WHT-PWD-100",
    offers: ["Green Blend Combo"],
    image: "wheatGrass"
  },
  {
    id: 17,
    name: "Spirulina Powder",
    brand: "Taurus",
    price: 899,
    salePrice: 749,
    catId: 2,
    subCatId: 4,
    description: "Clean spirulina powder intended for shakes and nutrition routines.",
    faqs: ["Can I add it to juice?", "Does it have a strong taste?", "How much should I use?"],
    ingredients: "Spirulina",
    boxSize: "100g",
    material: "Black tin",
    sku: "SPI-PWD-100",
    offers: ["Superfood Stack Offer"],
    image: "greenPowder"
  },
  {
    id: 18,
    name: "Psyllium Husk",
    brand: "Taurus",
    price: 499,
    salePrice: 429,
    catId: 2,
    subCatId: 4,
    description: "Premium psyllium husk for everyday fiber intake.",
    faqs: ["How much water should I take with it?", "Can I use it daily?", "Best time to consume?"],
    ingredients: "Psyllium Husk",
    boxSize: "250g",
    material: "Paper canister",
    sku: "PSY-HSK-250",
    offers: ["Gut Health Combo"],
    image: "husk"
  },
  {
    id: 19,
    name: "Mulethi Powder",
    brand: "Taurus",
    price: 599,
    salePrice: 499,
    catId: 2,
    subCatId: 4,
    description: "Single-ingredient mulethi powder for herbal use and blends.",
    faqs: ["Can I mix it in warm water?", "Can I take it with honey?", "How much should I use?"],
    ingredients: "Mulethi",
    boxSize: "100g",
    material: "Glass jar",
    sku: "MUL-PWD-100",
    offers: ["Herbal Powder Combo"],
    image: "haldi"
  },
  {
    id: 20,
    name: "Neem Powder",
    brand: "Taurus",
    price: 549,
    salePrice: 449,
    catId: 2,
    subCatId: 4,
    description: "Pure neem powder suitable for internal herbal use or blends.",
    faqs: ["Can I mix it with warm water?", "What is the serving size?", "Is it bitter?"],
    ingredients: "Neem Leaves",
    boxSize: "100g",
    material: "Glass jar",
    sku: "NEE-PWD-100",
    offers: ["Cleanse Combo Deal"],
    image: "greenPowder"
  },
  {
    id: 21,
    name: "Turmeric Powder",
    brand: "Taurus",
    price: 399,
    salePrice: 349,
    catId: 2,
    subCatId: 4,
    description: "High-quality turmeric powder for kitchen and wellness use.",
    faqs: ["Can I use it in milk?", "Is it culinary grade?", "Can I use it daily?"],
    ingredients: "Turmeric",
    boxSize: "150g",
    material: "Black tin",
    sku: "TUR-PWD-150",
    offers: ["Combo with Golden Milk Mix"],
    image: "haldi"
  },
  {
    id: 22,
    name: "Amla Powder",
    brand: "Taurus",
    price: 549,
    salePrice: 469,
    catId: 2,
    subCatId: 4,
    description: "Versatile amla powder for drinks, blends, and wellness routines.",
    faqs: ["Can I take it with water?", "Can I mix it with honey?", "Is it sour in taste?"],
    ingredients: "Amla",
    boxSize: "150g",
    material: "Glass jar",
    sku: "AML-PWD-150",
    offers: ["Vitamin C Combo"],
    image: "amlapowder"
  },

  // 3. PERSONAL CARE - Face Care (5 products)
  {
    id: 23,
    name: "Turmeric Face Wash",
    brand: "Taurus",
    price: 599,
    salePrice: 499,
    catId: 3,
    subCatId: 5,
    description: "Daily face wash with herbal ingredients for a fresh cleanse.",
    faqs: ["Can I use it twice daily?", "Is it suitable for oily skin?", "Does it foam?"],
    ingredients: "Turmeric, Neem, Aloe Vera, Rose Water",
    boxSize: "100ml",
    material: "Pump bottle",
    sku: "TUR-FW-100",
    offers: ["Combo with Rose Toner"],
    image: "faceWash"
  },
  {
    id: 24,
    name: "Rose Toner",
    brand: "Taurus",
    price: 499,
    salePrice: 399,
    catId: 3,
    subCatId: 5,
    description: "A light facial mist made with pure rose water for daily refreshing use.",
    faqs: ["Can I spray it over makeup?", "Should I refrigerate it?", "Is it suitable for sensitive skin?"],
    ingredients: "Rose Water",
    boxSize: "50ml",
    material: "Glass spray bottle",
    sku: "ROS-TON-050",
    offers: ["Buy 2 Get 15% OFF"],
    image: "roseToner"
  },
  {
    id: 25,
    name: "Multani Mud Roller",
    brand: "Taurus",
    price: 649,
    salePrice: 549,
    catId: 3,
    subCatId: 5,
    description: "Easy-apply mineral clay mask stick for a smooth skincare routine.",
    faqs: ["How often should I use it?", "Can it be used on oily skin?", "How long should I keep it on?"],
    ingredients: "Multani Mitti, Rose, Aloe Vera",
    boxSize: "50g",
    material: "Roll-on stick",
    sku: "MUL-ROL-050",
    offers: ["Combo with Rose Toner"],
    image: "soilRoller"
  },
  {
    id: 26,
    name: "Neem Face Powder",
    brand: "Taurus",
    price: 449,
    salePrice: 379,
    catId: 3,
    subCatId: 5,
    description: "Herbal face powder that can be mixed into DIY masks.",
    faqs: ["Can I mix it with rose water?", "How often should I use it?", "Can I combine it with multani mitti?"],
    ingredients: "Neem, Tulsi",
    boxSize: "75g",
    material: "Glass shaker jar",
    sku: "NEE-FAC-075",
    offers: ["Face Ritual Combo"],
    image: "neemFacewash"
  },
  {
    id: 27,
    name: "Rose Face Mask Powder",
    brand: "Taurus",
    price: 549,
    salePrice: 469,
    catId: 3,
    subCatId: 5,
    description: "A soft powdered mask blend for at-home facial rituals.",
    faqs: ["What should I mix it with?", "How long should I leave it on?", "Can dry skin use it?"],
    ingredients: "Rose Petals, Multani Mitti, Sandalwood",
    boxSize: "100g",
    material: "Glass jar",
    sku: "ROS-MSK-100",
    offers: ["Skincare Trio Deal"],
    image: "pinkRose"
  },

  // 3. PERSONAL CARE - Hair & Body (6 products)
  {
    id: 28,
    name: "Hair Growth Oil",
    brand: "Taurus",
    price: 799,
    salePrice: 679,
    catId: 3,
    subCatId: 6,
    description: "Herbal hair oil crafted for scalp massage and routine care.",
    faqs: ["How often should I apply it?", "Can I leave it overnight?", "Is it suitable for all hair types?"],
    ingredients: "Bhringraj, Amla, Coconut Oil, Sesame Oil",
    boxSize: "100ml",
    material: "Amber glass bottle",
    sku: "HRG-OIL-100",
    offers: ["Hair Care Combo"],
    image: "bhringraj"
  },
  {
    id: 29,
    name: "Bamboo Sponge",
    brand: "Taurus",
    price: 299,
    salePrice: 249,
    catId: 3,
    subCatId: 6,
    description: "Soft cleansing sponge designed for gentle bath and face use.",
    faqs: ["Can it be reused?", "How do I clean it?", "Is it suitable for sensitive skin?"],
    ingredients: "Bamboo Fiber",
    boxSize: "1 unit",
    material: "Natural bamboo fiber",
    sku: "BAM-SPG-001",
    offers: ["Buy 2 Get 10% OFF"],
    image: "bambooHusk"
  },
  {
    id: 30,
    name: "Brahmi Hair Powder",
    brand: "Taurus",
    price: 549,
    salePrice: 469,
    catId: 3,
    subCatId: 6,
    description: "Traditional herbal hair powder for DIY scalp and hair packs.",
    faqs: ["Can I mix it with curd?", "How often can I use it?", "Can it be mixed with amla?"],
    ingredients: "Brahmi",
    boxSize: "100g",
    material: "Glass jar",
    sku: "BRA-HRP-100",
    offers: ["Hair Pack Combo"],
    image: "bhringraj"
  },
  {
    id: 31,
    name: "Hibiscus Hair Oil",
    brand: "Taurus",
    price: 749,
    salePrice: 629,
    catId: 3,
    subCatId: 6,
    description: "Nourishing herbal oil created for scalp massage and shine care.",
    faqs: ["Can I leave it overnight?", "Is it sticky?", "How often should I use it?"],
    ingredients: "Hibiscus, Coconut Oil, Amla",
    boxSize: "100ml",
    material: "Glass bottle",
    sku: "HIB-HRO-100",
    offers: ["Hair Ritual Offer"],
    image: "oil"
  },
  {
    id: 32,
    name: "Coconut Hair Mask",
    brand: "Taurus",
    price: 699,
    salePrice: 589,
    catId: 3,
    subCatId: 6,
    description: "Creamy hair mask for weekly nourishment and softness.",
    faqs: ["Can I use it before shampoo?", "How long should I keep it on?", "Can it be used on dry hair?"],
    ingredients: "Coconut, Aloe Vera, Hibiscus",
    boxSize: "150g",
    material: "Wide-mouth jar",
    sku: "COC-MSK-150",
    offers: ["Hair Care Bundle"],
    image: "oil"
  },
  {
    id: 33,
    name: "Olive Body Oil",
    brand: "Taurus",
    price: 699,
    salePrice: 579,
    catId: 3,
    subCatId: 6,
    description: "Smooth body oil for massage and daily post-bath application.",
    faqs: ["Can I use it daily?", "Is it suitable for dry skin?", "Can it be used for massage?"],
    ingredients: "Olive Oil, Almond Oil, Vitamin E",
    boxSize: "120ml",
    material: "Glass bottle",
    sku: "OLV-BDY-120",
    offers: ["Body Care Combo"],
    image: "oil"
  },

  // 4. DETOX & WELLNESS - Cleanse Kits (4 products)
  {
    id: 34,
    name: "Liver Cleanse Kit",
    brand: "Taurus",
    price: 1499,
    salePrice: 1299,
    catId: 4,
    subCatId: 7,
    description: "Curated herbal kit designed for a structured cleanse routine.",
    faqs: ["How many days does it last?", "What is included?", "How should I use it?"],
    ingredients: "Green Tea, Triphala, Milk Thistle, Lemon Peel, Ginger",
    boxSize: "1 kit",
    material: "Premium rigid box",
    sku: "LIV-KIT-001",
    offers: ["Free Wellness Guide"],
    image: "cleanseshake"
  },
  {
    id: 35,
    name: "Metabolism Powder",
    brand: "Taurus",
    price: 899,
    salePrice: 749,
    catId: 4,
    subCatId: 7,
    description: "A functional powder blend created for active daily routines.",
    faqs: ["Can I mix it with water?", "Best time to take it?", "Can it be combined with exercise?"],
    ingredients: "Green Tea, Cinnamon, Garcinia, Ginger",
    boxSize: "150g",
    material: "Black glass jar",
    sku: "MET-PWD-150",
    offers: ["Fitness Combo Deal"],
    image: "blackTin"
  },
  {
    id: 36,
    name: "Gut Health Kit",
    brand: "Taurus",
    price: 1299,
    salePrice: 1099,
    catId: 4,
    subCatId: 7,
    description: "Wellness bundle for simple daily digestive support routines.",
    faqs: ["What products are included?", "Can I take it every day?", "Is it easy to use?"],
    ingredients: "Psyllium Husk, Triphala, Fennel, Cumin, Mint",
    boxSize: "1 kit",
    material: "Kraft gift box",
    sku: "GUT-KIT-001",
    offers: ["Bundle Savings 15% OFF"],
    image: "digestion2"
  },
  {
    id: 37,
    name: "Kidney Detox Kit",
    brand: "Taurus",
    price: 1399,
    salePrice: 1199,
    catId: 4,
    subCatId: 7,
    description: "A curated herbal kit assembled for structured cleanse support.",
    faqs: ["How should I use the kit?", "How long does it last?", "Can it be taken with other products?"],
    ingredients: "Nettle, Dandelion, Coriander, Parsley, Lemon Peel",
    boxSize: "1 kit",
    material: "Rigid board box",
    sku: "KID-KIT-001",
    offers: ["Free Diet Chart"],
    image: "cleanseshake"
  },

  // 4. DETOX & WELLNESS - Beauty & Vitality (3 products)
  {
    id: 38,
    name: "Collagen Powder",
    brand: "Taurus",
    price: 999,
    salePrice: 849,
    catId: 4,
    subCatId: 8,
    description: "Beauty-focused powder blend for daily mix-in use.",
    faqs: ["Can I add it to smoothies?", "Does it have a strong taste?", "Can I use it every day?"],
    ingredients: "Plant Collagen Blend, Vitamin C, Amla",
    boxSize: "100g",
    material: "Glass jar",
    sku: "COL-PWD-100",
    offers: ["Beauty Bundle Offer"],
    image: "greenPowder"
  },
  {
    id: 39,
    name: "Beauty Glow Mix",
    brand: "Taurus",
    price: 899,
    salePrice: 759,
    catId: 4,
    subCatId: 8,
    description: "A colorful wellness blend intended for beauty-focused routines.",
    faqs: ["Can I mix it in water?", "Can I add it to yogurt?", "How much should I take?"],
    ingredients: "Beetroot, Amla, Hibiscus, Rose, Moringa",
    boxSize: "120g",
    material: "Glass jar",
    sku: "BTY-GLW-120",
    offers: ["Combo with Rose Toner"],
    image: "pinkRose"
  },
  {
    id: 40,
    name: "Joint Care Oil",
    brand: "Taurus",
    price: 799,
    salePrice: 679,
    catId: 4,
    subCatId: 8,
    description: "Ayurvedic massage oil for regular body care rituals.",
    faqs: ["Can I warm the oil before use?", "How often should I apply it?", "Can it be used for massage?"],
    ingredients: "Sesame Oil, Mahanarayan Blend, Turmeric, Garlic, Ginger",
    boxSize: "100ml",
    material: "Amber glass bottle",
    sku: "JNT-OIL-100",
    offers: ["Pain Care Combo"],
    image: "oil"
  },

  // 5. GIFTING & BUNDLES - Wellness Hampers (3 products)
  {
    id: 41,
    name: "Daily Wellness Hamper",
    brand: "Taurus",
    price: 999,
    salePrice: 899,
    catId: 5,
    subCatId: 9,
    description: "A curated hamper of everyday wellness essentials for gifting.",
    faqs: ["What comes in the hamper?", "Is gift packaging included?", "Can I add a message card?"],
    ingredients: "Moringa Powder, Herbal Tea, Immunity Blend",
    boxSize: "1 hamper",
    material: "Premium gift box",
    sku: "DWH-HMP-001",
    offers: ["Free Gift Note"],
    image: "gift"
  },
  {
    id: 42,
    name: "Kids Immunity Drink Mix",
    brand: "Taurus",
    price: 699,
    salePrice: 599,
    catId: 5,
    subCatId: 9,
    description: "Easy-to-mix drink blend created for a family-friendly daily routine.",
    faqs: ["How should I serve it?", "Can it be mixed with milk?", "What age group is it for?"],
    ingredients: "Moringa, Amla, Turmeric, Oats, Jaggery",
    boxSize: "100g",
    material: "Pouch jar",
    sku: "KID-DRK-100",
    offers: ["Family Combo Savings"],
    image: "turmericimmun"
  },
  {
    id: 43,
    name: "Energy Drink Mix",
    brand: "Taurus",
    price: 849,
    salePrice: 699,
    catId: 5,
    subCatId: 9,
    description: "A rich functional drink blend for active mornings and busy days.",
    faqs: ["Can I mix it with milk?", "Can I use it pre-workout?", "Does it taste sweet?"],
    ingredients: "Maca, Cacao, Oats, Dates, Seeds",
    boxSize: "150g",
    material: "Matte black tin",
    sku: "ENG-DRK-150",
    offers: ["Combo with Wellness Hamper"],
    image: "cleanseshake"
  }
];
